version: '3.8'

services:
  cempa_notify:
    container_name: cempa_notify
    image: cempa_notify:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@users_db:5432/postgres
    depends_on:
      - users_db

  users_db:
    container_name: users_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
