services:
  users_management_module:
    container_name: users_management_module
    image: users_management_module:1.0.0
    build: ./modulo_usuarios
    ports:
      - "4000:4000"
    environment:
      - DB_URL=sqlite:////app/data/db.sqlite
    volumes:
      - dbdata:/app/data

volumes:
  dbdata: {}
